### PR TITLE
File upload

### PR DESCRIPTION
**Pull request by benjaminlees**

### CODE REVIEW

**Comment by NataliaLKB** [comment]
@benjaminlees Happy to review this in the evening! Let me know if you can hold off merging it until then :smile: :octocat:

**Comment by benjaminlees** [comment]
@NataliaLKB thanks, gotta get it merged today though so Michael can have a go

**Comment by NataliaLKB** [comment]
Makes sense! I will have a look later regardless :). :+1:

**Comment by benjaminlees** [comment]
@NataliaLKB definitely do and then i will make another Pr with your edits, I have gone deeper into shot and can not test all our handlers, when I get the time.

**Pull request merged**
