### PR TITLE
update package.json and add package-lock file

### PR DESCRIPTION
**Pull request by emilyb7**
for latest NPM version

### CODE REVIEW

**Review by NataliaLKB — COMMENTED** [review]
This is good, but managing with yarn is so much easier. Just a tip, but your choice! 👍

**Comment by sofer** [comment]
@emilyb7 thank you so much taking this on and @NataliaLKB and @benjaminlees thank you so much for providing such timely support.

**Comment by sofer** [comment]
@emilyb7 looks like there is small conflict that needs resolving.

**Comment by emilyb7** [comment]
@sofer fixed! thank you :)

**Pull request merged**
